### ISSUE TITLE
Svg tag support

### ISSUE THREAD

**Issue by torrinworx** [Nefsen402/destam-dom#2]
I was messing around with inserting an svg file directly into the jsx syntax and noticed that the svg tag isn't supported:
```
[plugin:transform-literal-html] Invalid tag name: svg

/home/torrin/Repos/Personal/OpenGig.org/frontend/pages/Landing.jsx

    at jsxName (file:///home/torrin/Repos/Personal/OpenGig.org/node_modules/destam-dom/transform/htmlLiteral.js:32:11)
    at parse (file:///home/torrin/Repos/Personal/OpenGig.org/node_modules/destam-dom/transform/htmlLiteral.js:145:3)
    at transformBabelAST (file:///home/torrin/Repos/Personal/OpenGig.org/node_modules/destam-dom/transform/htmlLiteral.js:373:17)
    at transform (file:///home/torrin/Repos/Personal/OpenGig.org/node_modules/destam-dom/transform/htmlLiteral.js:382:2)
    at TransformPluginContext.transform (file:///home/torrin/Repos/Personal/OpenGig.org/vite.config.js.timestamp-1730645392059-eb7ae0b1cd3de.mjs:12:27)
    at PluginContainer.transform (file:///home/torrin/Repos/Personal/OpenGig.org/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:49086:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadAndTransform (file:///home/torrin/Repos/Personal/OpenGig.org/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:51918:27)
    at async viteTransformMiddleware (file:///home/torrin/Repos/Personal/OpenGig.org/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:61870:24
```

I wanted to have the svg inside a jsx component so that the styles/transform/other svg stuff could be reactive, I think this would make a good feature, but is there a better approach to something like this?

**Comment by Nefsen402** [comment]
Take a look at the examples:
 - https://github.com/Nefsen402/destam-dom/blob/main/examples/svg.jsx
 - https://github.com/Nefsen402/destam-dom/blob/main/examples/asteroids.jsx
